version: '3'
services:
  database:
    image: mysql:8.0.29
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pokeworld
    volumes:
      - database-sql:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  database-sql: